### ISSUE TITLE
_sleeveLength

### ISSUE THREAD

**Issue by nadavbh12** [katzi-tantush/typescript-shop-project#8]
don't you already have sleeveLength in Shirt? why are you defining new setter and getter functions?
https://github.com/katzi-tantush/typescript-shop-project/blob/9245019e201ca3278bed088a8aee827d76f14c39/Shop%20Typescript%20Project/TShirt.ts#L10

**Comment by katzi-tantush** [comment]
T shirts have shorter sleeves. if they were permitted to be longer as in the parent class, they wouldent be T shirts

**Comment by nadavbh12** [comment]
aha. can you not implement the getter, though?
