### ISSUE TITLE
type checking?

### ISSUE THREAD

**Issue by nadavbh12** [katzi-tantush/typescript-shop-project#9]
would you also need to check that valueToCheck is indeed a number? or does typescript do that?
https://github.com/katzi-tantush/typescript-shop-project/blob/9245019e201ca3278bed088a8aee827d76f14c39/Shop%20Typescript%20Project/Validator.ts#L12

**Comment by katzi-tantush** [comment]
typescript does indeed check it, though I will need in the future need to do runtime checks for user input. we'll see then if it was better to build all the checks into the program from the word go (which I suspect is was)
